// <auto-generated />
using Bridges.InfrastructureServices.Gateways.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bridges.WebService.Migrations
{
    [DbContext(typeof(BridgesContext))]
    [Migration("20200518213542_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Bridges.DomainObjects.BridgesPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CrossRiver")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BridgesPoints");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CrossRiver = "пруд в парке стадиона Красная Пресня",
                            Location = "Дружинниковская улица",
                            Name = "Мост пешеходный «1905 года»",
                            Year = "1981"
                        },
                        new
                        {
                            Id = 2L,
                            CrossRiver = "река Москва",
                            Location = "1-я Фрунзенская улица",
                            Name = "Мост пешеходный «Андреевский»",
                            Year = "2000"
                        },
                        new
                        {
                            Id = 3L,
                            CrossRiver = "река Сетунь",
                            Location = "улица Пырьева, дом 24",
                            Name = "Мост пешеходный «Балочный»",
                            Year = "1956"
                        },
                        new
                        {
                            Id = 4L,
                            CrossRiver = "пруд Серебряно-Виноградный",
                            Location = "городок имени Баумана",
                            Name = "Мост пешеходный «Бауманский-1»",
                            Year = "1964"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
